STATES = [
    {'name': 'Abia',       'capital': 'Umuahia',       'region': 'South East',    'lat': 5.532,  'lon': 7.486},
    {'name': 'Adamawa',    'capital': 'Yola',          'region': 'North East',    'lat': 9.326,  'lon': 12.398},
    {'name': 'Akwa Ibom',  'capital': 'Uyo',           'region': 'South South',   'lat': 4.867,  'lon': 8.268},
    {'name': 'Anambra',    'capital': 'Awka',          'region': 'South East',    'lat': 6.212,  'lon': 7.072},
    {'name': 'Bauchi',     'capital': 'Bauchi',        'region': 'North East',    'lat': 10.310, 'lon': 9.843},
    {'name': 'Bayelsa',    'capital': 'Yenagoa',       'region': 'South South',   'lat': 4.921,  'lon': 6.263},
    {'name': 'Benue',      'capital': 'Makurdi',       'region': 'North Central', 'lat': 7.337,  'lon': 8.754},
    {'name': 'Borno',      'capital': 'Maiduguri',     'region': 'North East',    'lat': 11.846, 'lon': 13.151},
    {'name': 'Cross River','capital': 'Calabar',       'region': 'South South',   'lat': 5.751,  'lon': 8.508},
    {'name': 'Delta',      'capital': 'Asaba',         'region': 'South South',   'lat': 5.703,  'lon': 5.933},
    {'name': 'Ebonyi',     'capital': 'Abakaliki',     'region': 'South East',    'lat': 6.317,  'lon': 8.113},
    {'name': 'Edo',        'capital': 'Benin City',    'region': 'South South',   'lat': 6.524,  'lon': 5.929},
    {'name': 'Ekiti',      'capital': 'Ado Ekiti',     'region': 'South West',    'lat': 7.623,  'lon': 5.221},
    {'name': 'Enugu',      'capital': 'Enugu',         'region': 'South East',    'lat': 6.524,  'lon': 7.518},
    {'name': 'Gombe',      'capital': 'Gombe',         'region': 'North East',    'lat': 10.290, 'lon': 11.173},
    {'name': 'Imo',        'capital': 'Owerri',        'region': 'South East',    'lat': 5.480,  'lon': 7.033},
    {'name': 'Jigawa',     'capital': 'Dutse',         'region': 'North West',    'lat': 12.288, 'lon': 9.789},
    {'name': 'Kaduna',     'capital': 'Kaduna',        'region': 'North West',    'lat': 10.510, 'lon': 7.442},
    {'name': 'Kano',       'capital': 'Kano',          'region': 'North West',    'lat': 12.002, 'lon': 8.591},
    {'name': 'Katsina',    'capital': 'Katsina',       'region': 'North West',    'lat': 12.988, 'lon': 7.607},
    {'name': 'Kebbi',      'capital': 'Birnin Kebbi',  'region': 'North West',    'lat': 11.678, 'lon': 4.069},
    {'name': 'Kogi',       'capital': 'Lokoja',        'region': 'North Central', 'lat': 7.800,  'lon': 6.733},
    {'name': 'Kwara',      'capital': 'Ilorin',        'region': 'North Central', 'lat': 8.500,  'lon': 4.550},
    {'name': 'Lagos',      'capital': 'Ikeja',         'region': 'South West',    'lat': 6.5244, 'lon': 3.3792},
    {'name': 'Nasarawa',   'capital': 'Lafia',         'region': 'North Central', 'lat': 8.490,  'lon': 8.520},
    {'name': 'Niger',      'capital': 'Minna',         'region': 'North Central', 'lat': 9.600,  'lon': 6.550},
    {'name': 'Ogun',       'capital': 'Abeokuta',      'region': 'South West',    'lat': 6.909,  'lon': 3.540},
    {'name': 'Ondo',       'capital': 'Akure',         'region': 'South West',    'lat': 7.083,  'lon': 5.183},
    {'name': 'Osun',       'capital': 'Oshogbo',       'region': 'South West',    'lat': 7.761,  'lon': 4.576},
    {'name': 'Oyo',        'capital': 'Ibadan',        'region': 'South West',    'lat': 7.377,  'lon': 3.947},
    {'name': 'Plateau',    'capital': 'Jos',           'region': 'North Central', 'lat': 9.896,  'lon': 8.858},
    {'name': 'Rivers',     'capital': 'Port Harcourt', 'region': 'South South',   'lat': 4.815,  'lon': 7.050},
    {'name': 'Sokoto',     'capital': 'Sokoto',        'region': 'North West',    'lat': 13.063, 'lon': 5.240},
    {'name': 'Taraba',     'capital': 'Jalingo',       'region': 'North East',    'lat': 8.917,  'lon': 11.365},
    {'name': 'Yobe',       'capital': 'Damaturu',      'region': 'North East',    'lat': 11.748, 'lon': 11.966},
    {'name': 'Zamfara',    'capital': 'Gusau',         'region': 'North West',    'lat': 12.171, 'lon': 6.663},
    {'name': 'FCT',        'capital': 'Abuja',         'region': 'North Central', 'lat': 9.0578, 'lon': 7.4951}
]
